### ISSUE TITLE
Is it possible to build this on Linux, I keep on not having required files

### ISSUE THREAD

**Issue by NSuer** [labstreaminglayer/App-EGIAmpServer#6]
Could you possibly give information on the build environment you are using? I can't seem to find multiple files. I need to be able to build this on Linux .

**Comment by NSuer** [comment]
An example would be #include "ui_EGIAmpWindow.h". I can't seem to find this file in the source code

**Comment by cboulay** [comment]
ui_EGIAmpWindow.h is a file that is created automatically by Qt, derived from the provided .ui file. Are you using CMake and is it finding Qt?

**Comment by NSuer** [comment]
Ok, this question actually helped a ton. Sorry I'm pretty new to CMake and QT.

**Comment by NSuer** [comment]
Ok I was able to figure it out, I hope you have a great day
