### ISSUE TITLE
Working on Mac OS?

### ISSUE THREAD

**Issue by BryanGonzalez262** [labstreaminglayer/App-EGIAmpServer#9]
Hey all, 

I'm working on integrating our EGI system with lsl based on the contents of this repo. I'm able to compile the files and create the EGI AmpServer.app. However, the figure in the readme file looks like a windows system but our netstation is running on mac computer. Has anyone successfully got this working on a mac computer? 

I was able to compile the app on a mac, but when I tried using wine to open it, the GUI just showed me the file directory

**Comment by cboulay** [comment]
I think it doesn't matter where NetStation is running as long as the computer running NetStation and the computer running this app are networked together. As far as I can recall, NetStation creates a service and this application creates a client to connect to that service.

**Comment by cboulay** [comment]
Sorry, I was saying NetStation above, but I think you _also_ need to run something called AmpServer and this is not enabled by default.

**Comment by vchamberland** [comment]
I don't know if the AmpServer LSL converter can be run on the same computer that runs NetStation. At our lab, we have a Windows laptop connected via network cable to the iMac running NetStation, and from this laptop we run AmpServer (and LSL LabRecorder as well).

**Comment by tstenner** [comment]
In theory, the app should work everywhere (Windows, MacOS, same Mac, Linux, Android).
In practice, it has only been tested on separate Windows PCs/Macs.

**Comment by BryanGonzalez262** [comment]
Ok, I'm now working on a separate windows machine and getting closer. LSL has been compiled and I am now attempting to configure the EGI AmperServer App in the CMake GUI. 
Qt5_DIR set to <..>/Qt/5.12.3/msvz2017_64/lib/cmake/Qt5 (where the Qt5Config.cmake file is)   

LSL Cmake Helpers have been included from ../labstreaminglayer/build/LSL/liblsl
Precompiled liblsl found in ../labstreaminglayer/build/LSL/liblsl
Found Boost: ../labstreaminglayer/build/LSL/liblsl/lslboost (found version "1.78.0")

(then i get:)
**CMake Error at: <..>/labstreaminglayer/build/LSL/liblsl/LSLCMake.cmake:262 (get_target_property):
get_target_property() called with non-existent target "Qt::qmake".
Call Stack (most recent call first):
<..>/labstreaminglayer/build/LSL/liblsl/LSLCMake.cmake: 210 (findQTInstallationTool)
CMakeLists.txt:38 (installLSLApp)**

Any idea how to resolve this??
